---
  - name: Copy and unarchive backend
    unarchive:
      src: ~/project/backend.tar.gz
      dest: ~/

  - name: Start Server
    shell:
      chdir: ~/backend/dist
      cmd: pm2 start main.js -f

  - name: Save pm2 process list
    shell:
      cmd: pm2 save