---
  - name: Copy and unarchive backend
    unarchive:
      src: ~/project/backend.tar.gz
      dest: ~/

  - name: Build
    shell:
      chdir: ~/backend/dist
      cmd: |
        npm i
        npm run build

  - name: Start Server
    shell:
      chdir: ~/backend
      cmd: pm2 start npm -- run start