---
  - name: Copy and unarchive backend
    unarchive:
      src: ~/project/backend.tar.gz
      dest: ~/

  - name: Run build
    shell:
      chdir: ~/backend
      cmd: node run build

  - name: Start Server
    shell:
      chdir: ~/backend
      cmd: "pm2 start npm -- run start"